# docker-compose.yml
version: '3.8'

services:
  # Laravel Application Service (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Guestbook
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080 # *** UPDATED: Matches Nginx host port ***
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306 # This is the internal container port for MySQL, not your host port
      DB_DATABASE: guestbook_db # <--- CHANGED HERE
      DB_USERNAME: user
      DB_PASSWORD: password
    depends_on:
      - db

  # Nginx Web Server Service
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80" # *** UPDATED: Host port 8080 -> Container port 80 ***
                 # You will access your app at http://localhost:8080
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    ports:
      - "3307:3306" # *** KEPT 3307:3306 as 3306 is used by XAMPP MySQL ***
                 # Host port 3307 -> Container port 3306
    environment:
      DB_DATABASE: guestbook_db # <--- CHANGED HERE
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

# Docker Volumes
volumes:
  db_data: