# .github/workflows/cd.yml
name: Laravel CD Pipeline

on:
  workflow_run:
    workflows: ["Laravel CI Pipeline"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Application Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Memulai Deployment di Server ---"

            echo "Logging into Docker Hub on EC2 instance..."
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            echo "Docker Hub login successful on EC2."

            # Pull image aplikasi "all-in-one" (sudah ada Nginx dan PHP-FPM)
            echo "Pulling latest all-in-one application Docker image: parisyashp31/guestbook-laravel:latest"
            docker pull parisyashp31/guestbook-laravel:latest

            # Pull image MySQL
            echo "Pulling MySQL Docker image: mysql:5.7"
            docker pull mysql:5.7

            echo "Stopping and removing existing containers (if running)..."
            docker stop guestbook-app || true
            docker rm guestbook-app || true
            docker stop guestbook-db || true
            docker rm guestbook-db || true

            #membuat jaringan custom
            echo "Creating custom Docker network 'guestbook-network'..."
            docker network create guestbook-network || true

            # Jalankan container database
            echo "Running new database container named 'guestbook-db'..."
            docker run -d \
              --name guestbook-db \
              --network guestbook-network \
              -p 3306:3306 \
              -e MYSQL_DATABASE=${{ secrets.DB_DATABASE }} \
              -e MYSQL_ROOT_PASSWORD=root_password \
              -e MYSQL_USER=${{ secrets.DB_USERNAME }} \
              -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
              mysql:5.7

            # Jalankan container aplikasi "all-in-one"
            echo "Running new all-in-one application container named 'guestbook-app'..."
            docker run -d \
              --name guestbook-app \
              --network guestbook-network \
              -p 80:80 \
              -e APP_NAME=Guestbook \
              -e APP_ENV=production \
              -e APP_DEBUG=false \
              -e APP_URL=http://${{ secrets.SSH_HOST }} \
              -e APP_KEY=${{ secrets.APP_KEY }} \
              -e DB_CONNECTION=mysql \
              -e DB_HOST=guestbook-db \
              -e DB_PORT=3306 \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              parisyashp31/guestbook-laravel:latest
            
            echo "Waiting for containers to fully start up (30 seconds)..."
            sleep 30
            
            echo "Running database migrations..."
            docker exec guestbook-app php artisan migrate --force

            echo "Running database seeders..."
            docker exec guestbook-app php artisan db:seed --force

            echo "--- Deployment Selesai! ---"